name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # здесь указыва ется имя вашей в етки

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3.3.0
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install --prefix webproj/

    - name: Build
      run: npm run build --prod --prefix webproj/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./webproj/docs
